### PR TITLE
the latest version of shannon_wang_puglisi_weber_bers_2004 uses membrane_fast_transient_outward_current_conductance

### PR DESCRIPTION
**Pull request by MauriceHendrix**
Metadata in cellml seems to have changed. (Test failure caused by Chaste pulling in latest cellml files)

### CODE REVIEW

**Comment by kwabenantim** [comment]
This fixes `TestMetadataCellmlModels` which was previously failing: https://github.com/Chaste/ApPredict/actions/runs/4364154900/jobs/7631129070

**Review by kwabenantim — APPROVED** [review]
Thanks @MauriceHendrix. Looks good to me.

**Comment by mirams** [comment]
I'm confused, what has changed with this model?
https://github.com/Chaste/cellml/commits/master/cellml/shannon_wang_puglisi_weber_bers_2004.cellml

**Comment by mirams** [comment]
All of the ApPredict models were supposed to be being imported from the www.github.com/Chaste/cellml before any recent changes... and the version that's imported shouldn't have changed anyway unless the submodule is updated!

**Comment by MauriceHendrix** [comment]
> All of the ApPredict models were supposed to be being imported from the [www.github.com/Chaste/cellml](http://www.github.com/Chaste/cellml) before any recent changes... and the version that's imported shouldn't have changed anyway unless the submodule is updated!

not sure why it wasn't picked up before tbh, but that model doesn't have the tag the tests tests for

> All of the ApPredict models were supposed to be being imported from the [www.github.com/Chaste/cellml](http://www.github.com/Chaste/cellml) before any recent changes... and the version that's imported shouldn't have changed anyway unless the submodule is updated!

The metadata tag disappeared a ling time ago in this commit:
https://github.com/Chaste/cellml/commit/e43401f3db20225961bc5d77232db99a7b2a4f09
I do notice that the name of the model has changed as well at some point, so I'm guessing it was possibly pulling in the wrong model compiled in chaste /heart/src/odes/cellml instead, but I'm not 100% sure

**Pull request merged**
