### PR TITLE
Remove build cache

### PR DESCRIPTION
**Pull request by kwabenantim**
This removes the build cache from the test workflow. Tests will now start with a fresh build directory each time to avoid incompatibilities with new [codegen](https://github.com/ModellingWebLab/chaste-codegen) releases.

### CODE REVIEW

**Comment by kwabenantim** [comment]
One test currently failing: 
https://github.com/Chaste/ApPredict/actions/runs/4357003508/jobs/7615762345

```
8/22 Test #543: TestMetadataCellmlModels ................***Failed    0.25 sec
Running 1 test

 ***** TestMetadataCellmlModels.hpp *****
Entering TestMetadataHasBeenCorrectlyTranslatedToChaste
Model 1: shannon_wang_puglisi_weber_bers_2004_model_updated

/home/runner/_work/ApPredict/ApPredict/Chaste/projects/ApPredict/test/TestMetadataCellmlModels.hpp:333: Error: Expected (HasAParameterForThisOrScalingFactorOfThis(p_chaste_cell, "membrane_transient_outward_current_conductance") == true), found (false != true)
/home/runner/_work/ApPredict/ApPredict/Chaste/projects/ApPredict/test/TestMetadataCellmlModels.hpp:175: Error: Test failed: 
Chaste error: ./ode/src/common/AbstractOdeSystemInformation.cpp:143: No parameter named 'membrane_transient_outward_current_conductance'.
Failed

Failed 1 of 1 test
Success rate: 0%

...

The following tests FAILED:
	543 - TestMetadataCellmlModels (Failed)
```

**Comment by mirams** [comment]
This is a bit confusing, that file should be pulled from the GitHub.com/Chaste/cellml and I wasn't aware any metadata or this test had changed...?

But also wants some thinking about - ApPredict pulls the whole GitHub.com/Chaste/cellml/ collection into the source before building, but now @MauriceHendrix has probably included them in a Chaste (weekly/nightly?) test build so we want to think about whether to do something similar or not here now... Probably more efficient to only convert the relevant ones now.

**Comment by kwabenantim** [comment]
Thanks @mirams. I'll pull them in from [Chaste/cellml](https://github.com/Chaste/cellml).

**Comment by kwabenantim** [comment]
#19 fixes `TestMetadataCellmlModels` which now passes: https://github.com/Chaste/ApPredict/actions/runs/4364154900/jobs/7631129070

**Comment by kwabenantim** [comment]
This no-build-cache workflow now passes as well: https://github.com/Chaste/ApPredict/actions/runs/4364933482/jobs/7632877049

**Review by MauriceHendrix — COMMENTED** [review]
I think a fresh build dir is the best approach even if it's a little slower

**Pull request merged**
