### PR TITLE
Update SetupModel.cpp

### PR DESCRIPTION
**Pull request by MauriceHendrix**
This brings bak a direct link between numbers and models, so that if you pass a number it doesn't use teh factory method. It passes `TestModelFactory` (and the other tests) without any changes to the tests.

### CODE REVIEW

**Comment by mirams** [comment]
I'm more confused? I thought Martin abandoned the idea of using PyCML again with latest ApPredict?

**Comment by mirams** [comment]
> I'm more confused? I thought Martin abandoned the idea of using PyCML again with latest ApPredict?

If we do want to do this, I think it should stay in a branch for Martin really rather than complicating `main` one

**Comment by MauriceHendrix** [comment]
> > I'm more confused? I thought Martin abandoned the idea of using PyCML again with latest ApPredict?
> 
> If we do want to do this, I think it should stay in a branch for Martin really rather than complicating `main` one

Did he? I understood he's trying to run stuff in en environment which doesn't have Python3 (and only C++11)
@martinjrobins ?

The branch was just meant for Martin to have a quick test, before I merge it back in really.

**Comment by martinjrobins** [comment]
thanks for doing this @MauriceHendrix. However, at the moment I'm hoping I won't need this. For the moment I'm using an older version of ApPredict (that roche has been using for a number of years) to accomplish the immediate task of incorporating a new cellml file. After this I plan to swap to using a dockerised appredict (that is the newer version) and I won't need the "numbers for model" thing anymore

**Comment by MauriceHendrix** [comment]
> thanks for doing this @MauriceHendrix. However, at the moment I'm hoping I won't need this. For the moment I'm using an older version of ApPredict (that roche has been using for a number of years) to accomplish the immediate task of incorporating a new cellml file. After this I plan to swap to using a dockerised appredict (that is the newer version) and I won't need the "numbers for model" thing anymore

ok in that case I'll close this.

**Pull request closed without merging**
